name: zerodrop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - openai
    - python-dotenv
    - composio 
    - openai-agents
    - openai-agents[litellm]
    - litellm
    - composio-openai-agents
